name: deployment-pipeline

on:
  push:
    branches:
      - main

  pull_request:

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: checkout scm
        uses: actions/checkout@v2

      - name: track short sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.0'

      - name: install some deps
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: build the app
        run: go build -o our-binary-${{ steps.vars.outputs.sha_short }} .

      - name: run vet and lint
        run: |
          go vet .
          golint .

      - name: run tests
        run: go test -v

      - name: upload binary
        uses: actions/upload-artifact@v3
        with:
          name: our-binary-${{ steps.vars.outputs.sha_short }}
          path: our-binary-${{ steps.vars.outputs.sha_short }}

    build-container:
      runs-on: ubuntu-latest
      needs: build

      steps:
      - name: checkout scm
        uses: actions/checkout@v2

      - name: track short sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: download binary
        uses: actions/download-artifact@v3
        with:
          name: our-binary-${{ steps.vars.outputs.sha_short }}

      - name: setup qemu
        uses: docker/setup-qemu-action@v2

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: glennadjrussell
          password: dckr_pat_jUyM2RIc9Zvh7LKj3PT36a6l8gk

      - name: login to docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: glennadjrussell
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: |
            glennadjrussell/our-binary:${{ steps.vars.outputs.sha_short }}
            glennadjrussell/our-binary:latest
            ghcr.io/glennadjrussell/our-binary:${{ steps.vars.outputs.sha_short }}
            ghcr.io/glennadjrussell/our-binary:latest
          build-args: |
            SHORT_SHA=${{ steps.vars.outputs.sha_short }}
            #outputs: type=docker,dest=/tmp/image.tar
          outputs: type=docker

            #      - name: upload tar
            #        uses: actions/upload-artifact@v3
            #        with:
            #          name: glennadjrussell/our-binary
            #          path: /tmp/image.tar

            #      - name: raw docker build
            #      - name: docker image ls
            #        run: docker image ls

      - name: gcloud setup
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }} 

      - name: gcloud setup
        uses: google-github-actions/setup-gcloud@v0

      - name: gcloud auth
        run: |
          gcloud auth configure-docker

      - name: publish to gcr
        run: |
          docker tag glennadjrussell/our-binary:${{ steps.vars.outputs.sha_short }} gcr.io/gh-pipeline/our-binary:${{ steps.vars.outputs.sha_short }}
          docker push gcr.io/gh-pipeline/our-binary:${{ steps.vars.outputs.sha_short }}

      - name: add comment
        uses: actions/github-script@v4
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `Container published to glennadjrussell/our-binary-${{ steps.vars.outputs.sha_short }}`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })


    pre-deploy:
      runs-on: ubuntu-latest
      needs: build-container

      defaults:
        run:
          working-directory: ./terraform

      steps:
      - name: checkout scm
        uses: actions/checkout@v2

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: terraform init
        id: init
        run: terraform init

      - name: terraform validate
        id: validate
        run: terraform validate -no-color
                
      - name: terraform fmt
        id: fmt
        run: terraform fmt -no-color

      - name: terraform plan
        id: plan
        run: terraform plan -no-color

      - name: update pull request comments
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style üñå\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ‚öôÔ∏è\`${{ steps.init.outcome }}\`
            #### Terraform Plan üìñ\`${{ steps.plan.outcome }}\`
            #### Terraform Validation ü§ñ\`${{ steps.validate.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

    deploy:
      # Only run when a merge happens
      runs-on: ubuntu-latest
      needs: pre-deploy
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      defaults:
        run:
          working-directory: ./terraform

      steps:
      - name: checkout scm
        uses: actions/checkout@v2

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: terraform init
        id: init
        run: terraform init

      - name: terraform validate
        id: validate
        run: terraform validate -no-color

      - name: terraform fmt
        id: fmt
        run: terraform fmt

      - name: terraform plan
        id: plan
        run: terraform plan -no-color

      - name: terraform apply
        id: apply
        run: terraform apply -auto-approve

